### ISSUE TITLE
Android O: We are not able to get Bluetooth Mac Address

### ISSUE THREAD

**Issue by lesn1kk** [thaliproject/Thali_CordovaPlugin_BtLibrary#110]
It looks like current solutions to this problem doesn't seem to resolve with proper Bluetooth Mac Address on Android O due to security policy.
However, it looks like using reflection not on `Android settings` but on `BluetoothManagerService` works just fine. 
More details [here](https://github.com/thaliproject/Thali_CordovaPlugin/issues/1956)

**Comment by jareksl** [comment]
fixed with https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/pull/111
