### ISSUE TITLE
Fix Incoming Bluetooth connections handshake

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/Thali_CordovaPlugin_BtLibrary#12]
with listeningn: https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/blob/master/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/BTListenerThread.java

There can be only one incoming handshake active at any given time. This should be changed to handle multiple handshake with array

**Comment by DrJukka** [comment]
initial implementation can be found from: https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/tree/story_001 needs testing for verifyinf that it works.

**Comment by DrJukka** [comment]
Tested the implementation with 5 devices, and Created PR.

**Comment by yaronyg** [comment]
Needs to publish this to bin tray and then create a fake pr in thali_cordovaplugin so we can test the fix in CI.

**Comment by yaronyg** [comment]
Was blocked on CI not working but has code review.

**Comment by vjrantal** [comment]
Merged to `master` and released to Bintray.
