### ISSUE TITLE
We need to log our unhandled exceptions

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin_BtLibrary#13]
We have an unhandled exception handler that isn't currently logging before passing the exception along. We need to fix that.

**Comment by tompaana** [comment]
Review against story_001 branch here: https://github.com/thaliproject/Thali_CordovaPlugin_BtLibrary/compare/story_001...story_001_tomi

**Comment by yaronyg** [comment]
Needs to test this and then can do a PR

**Comment by yaronyg** [comment]
Needs to test this and then can do a PR

**Comment by yaronyg** [comment]
Can you please resolve the merge conflict and submit this as a PR?

**Comment by yaronyg** [comment]
#17 will take care of this
