### ISSUE TITLE
BluePeerDiscoveryUtils.java int8ArrayToBluetoothAddress leading zero problem results in BluetoothManager.java .getRemoteDevice IllegalArgumentException "is not a valid Bluetooth address"

### ISSUE THREAD

**Issue by RoundSparrow** [thaliproject/Thali_CordovaPlugin_BtLibrary#50]
Before the return in the int8ArrayToBluetoothAddress method, try this sanity test:

```
    if (stringBuilder.toString().length() != "02:00:00:00:00:00".length())
        throw new RuntimeException("This method just sourced a malformed Bluetooth Address!");
```

My situation is a Bluetooth LE device with 40:88:05 as the starting part of the address. the third byte being less than 16 in value would require padding of a zero.

**Comment by RoundSparrow** [comment]
This method seems to work better, it pads any MAC address bytes less than 16 with a zero.  Also can eliminate the .toUpperCase() on the return line.

```
private static String int8ArrayToBluetoothAddress(int[] bluetoothAddressAsInt8Array) {
    StringBuilder stringBuilder = new StringBuilder();

    for (int i = 0; i < bluetoothAddressAsInt8Array.length; ++i) {
        // the uppercase "X" on String.format ensures it is uppercase letters, which is convention for a Bluetooth MAC Address
        stringBuilder.append(String.format("%02X", (bluetoothAddressAsInt8Array[i] & 0xff)));

        if (i < bluetoothAddressAsInt8Array.length - 1) {
            stringBuilder.append(BLUETOOTH_ADDRESS_SEPARATOR);
        }
    }

    return stringBuilder.toString();
}
```

Well, then it occurred to me that there might be a way to eliminate the loop entirely.  But I'm curious why the method is named "int8Array" when BLUETOOTH_ADDRESS_BYTE_COUNT == 6 in the code?  Is there ever really a situation where 8 bytes comes into play?  Are the only possible combinations 6 or 8 bytes?

Because the way to eliminate the loop entirely would be:

```
    return String.format("%02X:%02X:%02X:%02X:%02X:%02X",
        (bluetoothAddressAsInt8Array[0] & 0xff),
        (bluetoothAddressAsInt8Array[1] & 0xff),
        (bluetoothAddressAsInt8Array[2] & 0xff),
        (bluetoothAddressAsInt8Array[3] & 0xff),
        (bluetoothAddressAsInt8Array[4] & 0xff),
        (bluetoothAddressAsInt8Array[5] & 0xff)
    );
```

**Comment by yaronyg** [comment]
@RoundSparrow the owner of this is @tompaana and he is heads down on a different assignment through Wednesday, so hopefully he should be able to look at this on Thursday.

**Comment by tompaana** [comment]
Many thanks @RoundSparrow! Not only for the interest in the project, but the fix. I'll try to incorporate the fixes to master as soon as possible.
