### ISSUE TITLE
NativeTestApp ListAdapter notifyDataSetChanged crashes

### ISSUE THREAD

**Issue by RoundSparrow** [thaliproject/Thali_CordovaPlugin_BtLibrary#51]
On devices running Android 5.1 and 6.0 - I'm having random crashes related to threading and notifyDataSetChanged() of the Peer List.  Stress testing the app by stopping and starting multiple peers.

I've had little success so far in tracking down where in the code this is being caused.  I wanted to open an issue in case others wanted to chime in.

**Comment by tompaana** [comment]
Did this happen in `PeerListFragment.onDataChanged` or `PeerListFragment.onPeerRemoved`? I wonder if this is due to `notifyDataSetChanged` being called concurrently from different threads.

**Comment by tompaana** [comment]
There is now a possible fix. Hope you have time to test it at some point.

**Comment by yaronyg** [comment]
We aren't seeing this repro anymore so we are closing. Please re-open if the bug returns. Thanks!

**Comment by RoundSparrow** [comment]
That's fine. I haven't had time to retest.  I wish I could figure out how I was triggering it - as one day I seemed to be able to do it almost on command ;)
