### ISSUE TITLE
DiscoveryManager.java logic on WiFi onP2pDeviceListChanged ignoring peers

### ISSUE THREAD

**Issue by RoundSparrow** [thaliproject/Thali_CordovaPlugin_BtLibrary#52]
Regarding source file: [DiscoveryManager.java](../tree/master/BtConnectorLib/btconnectorlib2/src/main/java/org/thaliproject/p2p/btconnectorlib/DiscoveryManager.java)
Method: onP2pDeviceListChanged

I witness that this code's logic is if the already-known peers list returns null - it does nothing.  It does not add the peer into the PeerList as a previously unknown peer.   Is this intentional?

I have WiFi only peers (that lack Bluetooth LE) that don't show up on the PeerList GUI...

**Comment by tompaana** [comment]
This is intentional - we only accept the peers whose service we have discovered. However, the service discovery tends to be slow and unreliable. So onP2pDeviceListChanged just keeps the peers alive. Without it we might lose the peers that we know are still around.
