### ISSUE TITLE
BluetoothServerThread.java run() method logic when "Failed to start listening"

### ISSUE THREAD

**Issue by RoundSparrow** [thaliproject/Thali_CordovaPlugin_BtLibrary#53]
I have an Android 5.0 device that this failed to listen, and the thread seems to just endlessly loop failing over and over as fast as possible.

Nothing appears in the LOG tab of the Native Test APP to show the failure.  No messages at all that I can find in the GUI to reflect the failure to listen.

My concern is how the library loops endlessly and doesn't seem to exit.  But for reference, here is the Exception detail:
java.io.IOException: Error: -1
                                                                                                                                               android.bluetooth.BluetoothAdapter.createNewRfcommSocketAndRecord(BluetoothAdapter.java:1215)
                                                                                                                                                   at android.bluetooth.BluetoothAdapter.listenUsingInsecureRfcommWithServiceRecord(BluetoothAdapter.java:1162)

**Comment by tompaana** [comment]
Fix pushed to separate branch. Please reopen if you are not happy with the resolution.
