### ISSUE TITLE
Connection timeout is not stopping BluetoothClientThread connection attempts

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin_BtLibrary#58]
When the connection timeout occurs there is a call to BluetoothClientThread.shutdown() method where mIsShuttingDown flag is set. This flag is checked in the BluetoothClientThread.tryToConnect() method after every connection attempt and when it is set no other attempt is made.
The issue is that both methods (tryToConnect and shutdown) are synchronized which means that if we are trying to connect and connection timeout is reached the call to shutdown() waits until we leave tryToConnect() which means that the timeout is ignored. It may lead to further errors if the connection is established as we may get information in listener that connection is established and it is timed out.

**Comment by tompaana** [comment]
Removing synchronized keyword from `shutdown` method should be enough, I believe. EDIT: No, `close` shouldn't be synchronized either.

**Comment by czyzm** [comment]
I suppose two step approach is needed - only setting the mIsShuttingDown flag should be not synchronized. Reseting mListener and calling close() should still be synchronized.

**Comment by tompaana** [comment]
But: `BluetoothSocket.close` call should not be synchronized when `BluetoothSocket.connect` is, because `connect` call blocks. Maybe only the part where we set listener to null should be synchronized.

**Comment by tompaana** [comment]
@czyzm: Could you check if my fix above makes sense?

**Comment by czyzm** [comment]
@tompaana: Change looks ok for me

**Comment by tompaana** [comment]
@czyzm: That's good and thank you. This was a good find.
