### ISSUE TITLE
No check whether filtering and scan batching is supported.

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin_BtLibrary#60]
When we start discovery or advertisement using DiscoveryManger.start() there is a check done BluetoothAdapter.isMultipleAdvertisementSupported(). However, during operation we are using filters and scan batching and for those we are not checking if they are supported. As result, on devices not supporting those after issuing start() we get immediately call of scan callback informing that feature is not supported.

We should also issue following checks:
BluetoothAdapter.isOffloadedScanBatchingSupported()
BluetoothAdapter.isOffloadedFilteringSupported()

See also: https://newcircle.com/s/post/1697/android_lollipop_bluetooth_andevcon

**Comment by yaronyg** [comment]
The obvious punishment for finding a bug is.... :)
