### ISSUE TITLE
Interface naming, usage  & placement needs to be changed

### ISSUE THREAD

**Issue by DrJukka** [thaliproject/Thali_CordovaPlugin_BtLibrary#7]
We need to change the Callback-interface to be named something more specific.

We need to implement the interface outside the class definition for the plugin entry point

We should re-use the interfaces, and remove any interfaces that implement similar functionality.

**Comment by tompaana** [comment]
Duplicate of #17

**Comment by tompaana** [comment]
All taken care of by #17
