### ISSUE TITLE
Instrumentation tests: toggling Bluetooth and WiFi not handling intermediate states

### ISSUE THREAD

**Issue by czyzm** [thaliproject/Thali_CordovaPlugin_BtLibrary#70]
The toggleBluetooth and toggleWifi methods used in instrumentation tests are not correctly handling intermediate states (turning on and turning off). They are using "isEnabled" method which is OK for turning on but not for turning off because it assumes the media is turned off even if it is still turning off. We should check the state directly.

**Comment by yaronyg** [comment]
I vaguely remember even complaining about this. The real question is, can we fix isEnabled?

**Comment by czyzm** [comment]
I treat it as an issue in the instrumentation tests only. This is because we are turning on/off bluetooth and wifi multiple times in a row and not handling the real states results in tries to, e.g. enable bluetooth while it is still turning off.

Of course, the isEnable() method is also used in production code but it is done in a way that is safe (just to check if we can proceed with some operation, not if we can turn it on/off again).

**Comment by czyzm** [comment]
Created PR #73
