### ISSUE TITLE
Couldn't post runnable to main thread in BluetoothConnector onIncomingConnectionConnected

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin_BtLibrary#88]

**Comment by evabishchevich** [comment]
Found out the place where our app just stops.
I haven't possibility to check my assumption because tests passed 3 times in a row but they won't pass reliably without fix. 
This is my p0 issue for tomorrow

**Comment by vasilevskayaem** [comment]
can't reproduce, probably it was connected with deadlock bug that was fixed some time ago

**Comment by evabishchevich** [comment]
@vasilevskayaem Looks right

**Comment by evabishchevich** [comment]
@yaronyg I close that. The reason should be in our deadlocks
