### ISSUE TITLE
Why doesn't BTLibrary put itself in the right location?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin_BtLibrary#93]
Due to the issues with bintray I built thali Thali_CordovaPlugin_BtLibrary/BtConnectorLib using './gradlew build install' from the command line. This worked but it put the final output into:

/Users/yarongoland/.m2/repository/org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.4-alpha3/ where the pom and aar file are.

Notice the name. 0.3.4.

Now just to make sure I'm not confused I manually went in and deleted the 0.3.4-alpha3 parent directory and reran the build install and sure enough it's back.

Shouldn't the directory be 0.3.5? Because when I try to build Thali_CordovaPlugin it fails looking for 0.3.5-alpha3 and when I check Bintray I see that we published there 0.3.5-alpha3.

So where did 0.3.4 come from?

**Comment by vasilevskayaem** [comment]
I reloaded lib to bintray, the right location for aar and pom file in bintray is /org/thaliproject/p2p/btconnectorlib/btconnectorlib2/<version name>

so for 0.3.5-alpha3 right directory in bintray is org/thaliproject/p2p/btconnectorlib/btconnectorlib2/0.3.5-alpha3/

if you manually generate it you should change in settings.gradle gradle.ext.version from 0.3.4-alpha3 to 0.3.5-alpha3
