### ISSUE TITLE
Fix deadlock in BlePeerDiscoverer and DiscoveryManager

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin_BtLibrary#97]
https://gist.github.com/evabishchevich/82d4b3c917e06898dc43f88014f6dfaa

**Comment by yaronyg** [comment]
@evabishchevich Isn't this fixed?

**Comment by evabishchevich** [comment]
PR thaliproject/Thali_CordovaPlugin_BtLibrary#98
